### ISSUE TITLE
Transition from macOS 13 to macOS 14

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/aria-at-gh-actions-helper#18]
At the time of writing, [this project uses macOS 13 to collect responses from VoiceOver](https://github.com/bocoup/aria-at-gh-actions-helper/blob/0eca41642388ee547e62fec9d9a72233bbc16eb8/.github/workflows/voiceover-test.yml#L44). However, [GitHub Actions offers macOS 14](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners). This project should upgrade to macOS 14 in order to provide more relevant data.

**Comment by gnarf** [comment]
We are now supporting both 13 and 14
