### ISSUE TITLE
Update Actions to Node.js 20

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/aria-at-gh-actions-helper#20]
This project currently defines two "dispatch" Actions, and they both use Node.js 18. GitHub issues the following warning when they are executed:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: guidepup/setup-action@0.15.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

It's not clear why GitHub reports that Node.js 16 is in use, but in any event, we should follow the recommendation to update to Node.js 20.

**Comment by outofambit** [comment]
closed by #29
