### ISSUE TITLE
Find storage for the .zip files needed by workflow.

### ISSUE THREAD

**Issue by gnarf** [bocoup/aria-at-gh-actions-helper#6]
Currently, we are just committing the zip file containing the configured nvda-portable installation to the repo, and it is just barely big enough to trigger github's warning about large files.

```
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File nvda-portable/2023.3.zip is 54.58 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com/.
```

`git lfs` is an addon to git that enables a "large files" storage bucket to store these sorts of things.  the LFS method is pretty clean for working with the files, using some tooling we basically inform the `.gitattributes` file to track `*.zip` and it should "just work" (by enabling some `with: lfs: true` in the workflows)

LFS does come with a small amount of a contributor burden, as `git-lfs` is not a core part of git: https://git-lfs.com/ and requires initializing for the repo.

It also becomes harder to push these files into the repo from a fork (if you don't have push access to the LFS of the parent repo)

LFS on github comes with 1 gig of free storage/transfer per month per "account" - I'm not sure how many other bocoup projects might use this, but it is a concern: https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage#about-billing-for-git-large-file-storage

--------

The other solution to this problem would be to store the .zip files in some external bucket (s3 / or any other high availability static web host) and fetch them with `curl` or something similar.  I feel like this solution is even HARDER to contribute to (requires setup/admin/backend keys to upload new files), and much more prone to intermittent mistakes (for some reason being unable to fetch the zip).  This version of the solution is definitely going to require some monthly service charges (for the s3 bucket, or whatever equivalent)

--------

My preference would generally be git lfs, which should be easy enough to enable (I think I just need to push the file into the LFS)

**Comment by jugglinmike** [comment]
Thanks for this write-up, @gnarf!

Now that we've deployed support for automated AT response collection in ARIA-AT App, this repository is on the critical path of that site's core functionality. In my mind, that makes its presence under Bocoup's GitHub organization unideal. I'd like to relocate this repository to the W3C GitHub organization in the near future. (cc @ccanash)

I'm mentioning this because while Bocoup can probably approve allocating the requisite GitHub LFS quota to this project, I don't know if the W3C can make such a commitment. We can certainly ask, though I'll bet they'd appreciate an estimate of our usage over time. Could you make such an estimate?

Barring that, I imagine that they have a process for provisioning storage space on an FTP server or similar, and that it probably will take some time to secure that. We can inquire about it in the same message that we ask about LFS.

I would also like to ask about the motivation for storing binaries in the first place, if only to create a public record. It seems like if we could build this nvda-portable on-demand, then we'd alleviate the problem of storing binaries.

- Is the process prohibitively time-consuming? (i.e. would it significantly impact the time to collect AT responses?)
- Is the process prohibitively difficult to automate? (And do we have any experience with general-purpose Windows GUI scripting tools?)
- Is there some other consideration that precludes building on-demand?

**Comment by gnarf** [comment]
> I'm mentioning this because while Bocoup can probably approve allocating the requisite GitHub LFS quota to this project, I don't know if the W3C can make such a commitment. We can certainly ask, though I'll bet they'd appreciate an estimate of our usage over time. Could you make such an estimate?

If we keep updating it seems NVDA puts out about 3 major versions a year, at ~50meg (lets just round to 100 for extra padding) puts like ~300meg storage per year if we want to support past versions at all - with ~100meg transfer per suite run in the automation.  It's >very< small and low-bandwidth this way.

> I would also like to ask about the motivation for storing binaries in the first place, if only to create a public record. It seems like if we could build this nvda-portable on-demand, then we'd alleviate the problem of storing binaries.
> 
> * Is the process prohibitively time-consuming? (i.e. would it significantly impact the time to collect AT responses?)
> * Is the process prohibitively difficult to automate? (And do we have any experience with general-purpose Windows GUI scripting tools?)
> * Is there some other consideration that precludes building on-demand?

The "portable" install has a few advantages over the normal install, mainly not needing to be installed in system/protected folders/go through MSI installer scripting (which I have very little experience with, however a friend of mine is an old pro and I've borrowed that expertise before).  The other big advantage is that it bundles the NVDA-automation python scripts from the PAC project with it, something that I've had trouble installing and getting working even in the "global install" situation.

I haven't investigated it, but it is possible that we could download the latest nvda-portable from nvda release page, copy the addon (which we checked out already) into the proper folder, install the ini file with the correct settings and things should "just work".  I don't think this would be >that< much processing time.  However, I've also noticed trouble getting the addon to properly install when NVDA updates it's internal "api version", it needs some updating of the addon to bundle a new package.  This is why I felt that having the "build a new portable with the speech collector api addon already configured" step was the simplest to understand at the time.  I am also a little worried about the last version of NVDA adding the "addon store" step, it was [actually a bit of trouble](https://github.com/Prime-Access-Consulting/nvda-at-automation/issues/37#issuecomment-1714822546) for me to get it working again after they changed that (not sure if there was a signing thing or just filesystem permissions things???)

**Comment by gnarf** [comment]
> If we spend 1/10th of the 1-gigabyte monthly transfer budget for every collection job, then I think we could easily exceed the limit.

yeah - you are quite right here, my brain was just in the wrong scale on order of magnitude here, for some reason I thought it was closer to 1000 runs per month



> Do you happen to know what constitutes "transfer" in this case? Specifically, I'm wondering whether cloning from the GitHub Actions environment is metered

I have no idea, nor can I find specific reference in the documentation.  I've not used github's LFS service before, I'm only familiar with it from some bitbucket unity projects.

As another option that might be available, maybe we can bundle the nvda-portable zips as a "release" zip attachment in another project (or even this one)

**Comment by jugglinmike** [comment]
> As another option that might be available, maybe we can bundle the nvda-portable zips as a "release" zip attachment in another project (or even this one)

That sounds like the most practical idea, yet! I suppose creating a GitHub repository dedicated to this purpose would be ideal (since we might move this GitHub Workflow to ARIA-AT in the short-term and we will likely switch to a different cloud computing platform in the medium-term).

**Comment by gnarf** [comment]
@jugglinmike could you stub out a repository for this purpose, and give me proper team rights to push releases?

**Comment by jugglinmike** [comment]
Sure, it's at https://github.com/bocoup/aria-at-automation-nvda-builds . There should be an invitation to become an administrator of that project in your inbox.
